name: Front-end e2e test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - v2.0
defaults:
  run:
    working-directory: web

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: cache yarn.lock
        uses: actions/cache@v2
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp yarn.lock package-temp-dir
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}
      - name: Setup Node.js environment for Front-end
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn

  web-e2e:
    name: Front-end e2e test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: restore cache from yarn.lock
        uses: actions/cache@v2
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: Start Front-end then test
        run: yarn test:e2e
    needs: setup
