name: Front-end e2e test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - v2.0
defaults:
  run:
    working-directory: web

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/web/yarn.lock') }}
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        
      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn

  web-e2e:
    name: Front-end e2e test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache from node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install
        
      - name: Start Front-end then test
        run: yarn test:e2e
    needs: setup
